# Generated by Django 2.2.19 on 2023-02-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='city',
            name='timezone',
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
