# Generated by Django 2.2.19 on 2023-02-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytime', '0002_auto_20230211_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone_name', models.CharField(max_length=50)),
                ('timezone_delta', models.FloatField()),
            ],
        ),
    ]
