# Generated by Django 2.2.19 on 2023-02-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citytime', '0003_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timezones', to='citytime.TimeZone'),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='timezone_delta',
            field=models.FloatField(unique=True),
        ),
    ]
